velocity_controller1:
  type: "velocity_controllers/JointVelocityController"
  joint: 1_wheel
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
velocity_controller2:
  type: "velocity_controllers/JointVelocityController"
  joint: 2_wheel
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
velocity_controller3:
  type: "velocity_controllers/JointVelocityController"
  joint: 3_wheel
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
velocity_controller4:
  type: "velocity_controllers/JointVelocityController"
  joint: 4_wheel
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
stepper_motor_controller:
  type: "position_controllers/JointPositionController"
  joint: stepper_motor_to_wheel_hub
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
servo_motor_1_controller:
  type: "position_controllers/JointPositionController"
  joint: servo_motor_1_to_link2
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
servo_motor_2_controller:
  type: "position_controllers/JointPositionController"
  joint: servo_motor_2_to_link3
  pid:
    p: 1.0
    i: 0.0
    d: 0.0    
servo_motor_3_controller:
  type: "position_controllers/JointPositionController"
  joint: servo_motor_3_to_gripper_base
  pid:
    p: 1.0
    i: 0.0
    d: 0.0    